// packages/react-playground/src/App.tsx
import { useMemo, useState } from 'react'

import { ReactLoader } from '@dev-to/react-loader'

export default function App() {
  const [origin, setOrigin] = useState('http://localhost:5173')
  const [name, setName] = useState('RemoteCard')

  const componentProps = useMemo(() => ({ title: 'Loaded by @dev-to/react-loader' }), [])

  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ margin: 0, fontSize: 20 }}>@dev-to/react-playground</h1>
      <p style={{ margin: '8px 0 16px', color: '#475569' }}>
        Rspack host app loading a remote component from Vite dev server.
      </p>

      <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
        <label style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <span style={{ width: 64, color: '#0f172a' }}>Origin</span>
          <input
            value={origin}
            onChange={e => setOrigin(e.target.value)}
            style={{ width: 320, padding: '6px 10px' }}
          />
        </label>

        <label style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <span style={{ width: 64, color: '#0f172a' }}>Name</span>
          <input
            value={name}
            onChange={e => setName(e.target.value)}
            style={{ width: 200, padding: '6px 10px' }}
          />
        </label>
      </div>

      <div style={{ marginTop: 16, padding: 16, borderRadius: 12, background: '#fff', border: '1px solid #e2e8f0' }}>
        <ReactLoader origin={origin} name={name} componentProps={componentProps} />
      </div>
    </div>
  )
}

// packages/archived/vue-playground/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { VueLoader } from '@dev-to/vue-loader'

const origin = ref('http://localhost:5173')
const name = ref('RemoteCard')
const componentProps = { title: 'Loaded by @dev-to/vue-loader' }
</script>

<template>
  <div class="app">
    <h1>@dev-to/vue-playground</h1>
    <p class="subtitle">
      Vite host app loading a remote component from a Vite dev server.
    </p>

    <div class="controls">
      <label>
        <span>Origin</span>
        <input v-model="origin" />
      </label>
      <label>
        <span>Name</span>
        <input v-model="name" />
      </label>
    </div>

    <div class="preview">
      <VueLoader :origin="origin" :name="name" :component-props="componentProps" />
    </div>
  </div>
</template>

<style scoped>
.app {
  padding: 24px;
  color: #0f172a;
}

.subtitle {
  margin: 8px 0 16px;
  color: #475569;
}

.controls {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  align-items: center;
}

label {
  display: flex;
  gap: 8px;
  align-items: center;
}

label span {
  width: 64px;
  color: #0f172a;
}

input {
  width: 280px;
  padding: 6px 10px;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
}

.preview {
  margin-top: 16px;
  padding: 16px;
  border-radius: 12px;
  background: #ffffff;
  border: 1px solid #e2e8f0;
}
</style>
